// Copyright (c) 2026 John Mark White -- US Amateur Radio License: W4KUS
//
// Licensed under the MIT License - see LICENSE file for details.

#pragma once

#include <type_traits>
#include <functional>
#include <cstdio>

#include "block.h"
#include "rm-math.h"

namespace dsp { namespace endpoints {

/*! \brief Text File Sink
 *
 * A text file sink for dumping samples to a text file in a format suitable
 * for importing into Octave or Matlab. This is intended for analying signals after iteration
 * through a chain.
 *
*/

template<typename T, typename B>
class text_file_sink : public block<B>
{
    static_assert(std::is_floating_point<T>::value == std::true_type());
    static_assert(is_block_func_v<B>);

public:

    //! Create a new instance.
    //! @param [in] fn        The filename to use for the samples.
    //! @param [in] openFile  Whether or not to open the file during contruction. By default the
    //!                       file is opened to follow the RAII design pattern but this may not be
    //!                       suitable in certain situations. If so, then pass in *false* and use the
    //!                       *setup()* method.
    //! @warning  If you do open it during contruction and it fails, an assert is generated if compiled
    //!           for debugging; otherwise, it will silently fail which eventually leads to a segfault.
    text_file_sink(const char *fn, bool openFile = true) : block<B> { TYPE_SINK }, m_FileName { fn }, m_File { nullptr }
    {
        assert(fn);
        block<B>::process = std::bind(&text_file_sink::handler, this, std::placeholders::_1, std::placeholders::_2);

        if (openFile)
        {
            if (!setup())
                assert(1);
        }
    }

    ~text_file_sink()
    {
        if (m_File) std::fclose(m_File);
    }

    //! Attempt to open the file.
    //! @return *true* if the file opened successfually or is alread opened; *false* otherwise.
    bool setup()
    {
        if (!m_File)
            m_File = std::fopen(m_FileName, "w");

        return static_cast<bool>(m_File);
    }

    //! Process incoming samples.
    //! @param [in] inBlock   The samples to print to a file
    //! @param [in] outBlock  Ignored.
    void handler(const util::aligned_ptr<T> &inBlock, util::aligned_ptr<T> &outBlock)
    {
        for (size_t i=0;i < inBlock.size();i++)
            std::fprintf(m_File, "%0.6f ", inBlock[i]);

        std::fflush(m_File);
    }

private:
    const char *m_FileName;
    FILE *m_File;
};

// complex specialization
template<>
class text_file_sink<rm_math::complex_f, dsp::func_cc> : public block<dsp::func_cc>
{
public:

    text_file_sink(const char *fn, bool openFile = true) : block { TYPE_SINK }, m_FileName { fn }, m_File { nullptr }
    {
        assert(fn);
        block::process = std::bind(&text_file_sink::handler, this, std::placeholders::_1, std::placeholders::_2);

        if (openFile)
        {
            if (!setup())
                assert(1);
        }
    }

    ~text_file_sink()
    {
        if (m_File) std::fclose(m_File);
    }

    bool setup()
    {
        if (!m_File)
            m_File = std::fopen(m_FileName, "w");

        return static_cast<bool>(m_File);
    }

    void handler(const util::aligned_ptr<rm_math::complex_f> &inBlock, util::aligned_ptr<rm_math::complex_f> &outBlock)
    {
        // In Octave/MatLab use this command to load a file with complex values
        // as generated by this function. Note the single quote at the end.
        // cell2mat(textscan(f, "%f"))'
        for (size_t i=0;i < inBlock.size();i++)
        {
            std::fprintf(m_File, "%0.6f", inBlock[i].real());

            if (inBlock[i].imag() >= 0)
                std::fprintf(m_File, "+");

            std::fprintf(m_File, "%0.6f", inBlock[i].imag());
        }

        std::fflush(m_File);
    }

private:
    const char *m_FileName;
    FILE *m_File;
};

using text_file_sink_ff = text_file_sink<float, dsp::func_ff>;
using text_file_sink_cc = text_file_sink<rm_math::complex_f, dsp::func_cc>;

}}
