/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(grcarrier_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ada1cc34bb821a68e6ff49d6f0b37f66)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radiomon/grcarrier_sync.h>
// pydoc.h is automatically generated in the build directory
#include <grcarrier_sync_pydoc.h>

void bind_grcarrier_sync(py::module& m)
{

    using grcarrier_sync    = ::gr::radiomon::grcarrier_sync;


    py::class_<grcarrier_sync, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<grcarrier_sync>>(m, "grcarrier_sync", D(grcarrier_sync))

        .def(py::init(&grcarrier_sync::make),py::arg("Kp"),py::arg("Ki"),D(grcarrier_sync,make))
        .def("Kp",&grcarrier_sync::Kp,D(grcarrier_sync,Kp))
        .def("Ki",&grcarrier_sync::Ki,D(grcarrier_sync,Ki));
}
