/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(grfirinterp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2a8359578a1cdb353dd77203f9ec9baf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radiomon/grfirinterp.h>
// pydoc.h is automatically generated in the build directory
#include <grfirinterp_pydoc.h>

template<typename T>
void bind_grfirinterp_template(py::module &m, const char *name)
{
    using grfirinterp = gr::radiomon::grfirinterp<T>;


    py::class_<grfirinterp,
            gr::sync_interpolator,
            gr::block,
            gr::basic_block,
            std::shared_ptr<grfirinterp>>(m, name)
        .def(py::init(&gr::radiomon::grfirinterp<T>::make), 
            py::arg("interpolate"),
            py::arg("adjustGain"))
        .def("interpolate", &grfirinterp::interpolate)
        .def("adjustGain", &grfirinterp::adjustGain);

}

void bind_grfirinterp(py::module &m)
{
    bind_grfirinterp_template<float>(m, "grfirinterp_f");
    bind_grfirinterp_template<gr_complex>(m, "grfirinterp_c");
}
