/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(grfirdecim.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e4d2045e3f8b45080601b4287d94a504)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radiomon/grfirdecim.h>
// pydoc.h is automatically generated in the build directory
#include <grfirdecim_pydoc.h>

template<typename T>
void bind_grfirdecim_template(py::module &m, const char *name)
{

    using grfirdecim = gr::radiomon::grfirdecim<T>;


    py::class_<grfirdecim,
            gr::sync_decimator,
            gr::block,
            gr::basic_block,
            std::shared_ptr<grfirdecim>>(m, name)
        .def(py::init(&gr::radiomon::grfirdecim<T>::make), py::arg("decimate"))
        .def("decimate", &grfirdecim::decimate);

}

void bind_grfirdecim(py::module &m)
{
    bind_grfirdecim_template<float>(m, "grfirdecim_f");
    bind_grfirdecim_template<gr_complex>(m, "grfirdecim_c");
}
