/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(grfirfilt.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c82acaa2a6f6bc3dfaa199b664d36f4c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radiomon/grfirfilt.h>
// pydoc.h is automatically generated in the build directory
#include <grfirfilt_pydoc.h>

template<typename T>
void bind_grfirfilt_template(py::module &m, const char *name)
{

    using grfirfilt = gr::radiomon::grfirfilt<T>;


    py::class_<grfirfilt,  
            gr::sync_block, 
            gr::block, 
            gr::basic_block,
            std::shared_ptr<grfirfilt>>(m, name)
        .def(py::init(&gr::radiomon::grfirfilt<T>::make));
}

void bind_grfirfilt(py::module &m)
{
    bind_grfirfilt_template<float>(m, "grfirfilt_f");
    bind_grfirfilt_template<gr_complex>(m, "grfirfilt_c");
}
