#include "cmdline.h"
#include <algorithm>


char *util::getCmdOption(char ** begin, char ** end, const std::string& option)
{
    char ** itr = std::find(begin, end, option);
    if (itr != end && ++itr != end)
    {
        return *itr;
    }

    return 0;
}

bool util::cmdOptionExists(char** begin, char** end, const std::string& option)
{
    return std::find(begin, end, option) != end;
}

void util::printReal(FILE *f, std::vector<float>  &vals)
{
    for (std::vector<float>::iterator it = vals.begin(); it != vals.end(); ++it)
        fprintf(f, "%0.6f ", *it);
}

void util::printReal(FILE *f, size_t num, const float *vals)
{
    for (size_t i=0;i < num;i++)
        fprintf(f, "%0.06f ", vals[i]);
}

void util::printComplex(FILE *f, std::vector<std::complex<float>> &vals)
{
    // In Octave/MatLab use this command to load a file with complex values
    // as generated by this function. Note the single quote at the end.
    // cell2mat(textscan(f, "%f"))'

    for (std::vector<std::complex<float>>::iterator it = vals.begin(); it != vals.end(); ++it)
    {
        fprintf(f, "%0.6f", it->real());

        if (it->imag() >= 0)
            fprintf(f, "+");

        fprintf(f, "%0.6fj ", it->imag());
    }
}

void util::printComplex(FILE *f, size_t num, const std::complex<float> *vals)
{
    // In Octave/MatLab use this command to load a file with complex values
    // as generated by this function. Note the single quote at the end.
    // cell2mat(textscan(f, "%f"))'

    for (size_t i=0;i < num;i++)
    {
        fprintf(f, "%0.6f", vals[i].real());

        if (vals[i].imag() >= 0)
            fprintf(f, "+");

        fprintf(f, "%0.6fj ", vals[i].imag());
    }
}
